definitions:
  triggering:
    push: &events
      events:
        - push
        - pull_request

workflows:
  meshingkit:
    name: MeshingKit Workflow
    environment:
      xcode: 26.0
      vars:
        XCODE_SCHEME: "MeshingKit"
        APP_ID: "MeshingKit"
    when:
      changeset:
        includes:
          - 'Sources'
          - 'Tests'
          - 'Package.swift'
          - '*.swift'
    triggering:
      <<: *events
    scripts:
      - name: Build Swift Package
        script: |
          #!/bin/zsh

          echo "Building MeshingKit..."

          # Basic swift build for the current platform
          swift build --target MeshingKit

      - name: Test Swift Package
        script: |
          #!/bin/zsh

          echo "Testing MeshingKit..."

          # Run tests with verbose output
          swift test --verbose

          # Generate code coverage report
          swift test --enable-code-coverage

      - name: Build with Xcode (Multi-Platform)
        script: |
          #!/bin/zsh

          declare -a DESTINATIONS=(
            "platform=iOS Simulator,name=iPhone 15"
            "platform=watchOS Simulator,name=Apple Watch Ultra 2 (49mm)"
            "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)"
            "platform=macOS"
            "platform=visionOS Simulator,name=Apple Vision Pro"
          )

          for DESTINATION in "${DESTINATIONS[@]}"
            do
              echo "Building for destination: $DESTINATION"
              xcodebuild clean build \
                -scheme "$XCODE_SCHEME" \
                -destination "$DESTINATION" \
                -skipPackagePluginValidation \
                -quiet
          done
    
