definitions:
  triggering:
    push: &events
      events:
        - push
        - pull_request

workflows:
  meshingkit:
    name: MeshingKit Workflow
    environment:
      xcode: 26.0
      vars:
        XCODE_SCHEME: "MeshingKit"
        APP_ID: "MeshingKit"
    when:
      changeset:
        includes:
          - 'Sources'
          - 'Tests'
          - 'Package.swift'
          - '*.swift'
    triggering:
      <<: *events
    scripts:
      - name: Lint Swift Code
        script: |
          #!/bin/zsh

          echo "Running SwiftLint..."

          # Install swiftlint if not available
          if ! command -v swiftlint &> /dev/null; then
            echo "Installing SwiftLint..."
            brew install swiftlint
          fi

          # Run swiftlint with strict mode
          swiftlint --strict

      - name: Build Swift Package
        script: |
          #!/bin/zsh

          echo "Building MeshingKit..."

          # Basic swift build for the current platform
          swift build --target MeshingKit

      - name: Test Swift Package
        script: |
          #!/bin/zsh

          echo "Testing MeshingKit..."

          # Run tests with verbose output
          swift test --verbose

          # Generate code coverage report
          swift test --enable-code-coverage

      - name: Download Metal Toolchain
        script: |
          #!/bin/zsh
          xcodebuild -downloadComponent MetalToolchain

      - name: Build with Xcode (Multi-Platform)
        script: |
          #!/bin/zsh

          declare -a DESTINATIONS=(
            "platform=iOS Simulator,name=iPhone 17 Pro"
            "platform=macOS"
          )

          for DESTINATION in "${DESTINATIONS[@]}"
            do
              echo "Building for destination: $DESTINATION"
              xcodebuild clean build \
                -project Sources/Meshin/Meshin.xcodeproj \
                -scheme Meshin \
                -destination "$DESTINATION" \
                -configuration Debug \
                -skipPackagePluginValidation \
                CODE_SIGN_IDENTITY="" \
                CODE_SIGNING_REQUIRED=NO \
                -quiet
          done
    
